[2024-07-25T16:12:17.514+0000] {processor.py:154} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:12:17.516+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:12:17.518+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:12:17.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:12:17.542+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:12:17.540+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:12:17.543+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:12:17.559+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-07-25T16:12:47.761+0000] {processor.py:154} INFO - Started process (PID=101) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:12:47.763+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:12:47.763+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:12:47.763+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:12:47.778+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:12:47.777+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:12:47.779+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:12:47.800+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-25T16:13:18.741+0000] {processor.py:154} INFO - Started process (PID=166) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:13:18.742+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:13:18.743+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:13:18.743+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:13:18.753+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:13:18.751+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:13:18.754+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:13:18.771+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-25T16:13:49.752+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:13:49.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:13:49.754+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:13:49.754+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:13:49.764+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:13:49.763+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:13:49.764+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:13:49.780+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-25T16:14:20.139+0000] {processor.py:154} INFO - Started process (PID=284) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:14:20.141+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:14:20.142+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:14:20.142+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:14:20.156+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:14:20.155+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:14:20.156+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:14:20.177+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-25T16:14:50.222+0000] {processor.py:154} INFO - Started process (PID=348) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:14:50.225+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:14:50.226+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:14:50.226+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:14:50.240+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:14:50.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:14:50.240+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:14:50.254+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-25T16:15:20.335+0000] {processor.py:154} INFO - Started process (PID=412) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:15:20.335+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:15:20.336+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:15:20.336+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:15:20.341+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:15:20.340+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:15:20.343+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:15:20.353+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2024-07-25T16:15:50.405+0000] {processor.py:154} INFO - Started process (PID=476) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:15:50.406+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:15:50.407+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:15:50.407+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:15:50.416+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:15:50.415+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:15:50.416+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:15:50.430+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-25T16:16:20.563+0000] {processor.py:154} INFO - Started process (PID=540) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:16:20.565+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:16:20.565+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:16:20.565+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:16:20.574+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:16:20.573+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:16:20.574+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:16:20.591+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-25T16:16:51.453+0000] {processor.py:154} INFO - Started process (PID=594) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:16:51.454+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:16:51.454+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:16:51.454+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:16:51.462+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:16:51.461+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:16:51.463+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:16:51.480+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-25T16:17:22.266+0000] {processor.py:154} INFO - Started process (PID=657) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:17:22.267+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:17:22.268+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:17:22.267+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:17:22.278+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:17:22.276+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:17:22.278+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:17:22.298+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-25T16:17:52.399+0000] {processor.py:154} INFO - Started process (PID=721) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:17:52.401+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:17:52.402+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:17:52.402+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:17:52.412+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:17:52.411+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:17:52.413+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:17:52.435+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-07-25T16:18:22.510+0000] {processor.py:154} INFO - Started process (PID=783) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:18:22.511+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:18:22.512+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:18:22.512+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:18:22.523+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:18:22.522+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:18:22.524+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:18:22.546+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-25T16:18:52.761+0000] {processor.py:154} INFO - Started process (PID=847) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:18:52.762+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:18:52.762+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:18:52.762+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:18:52.769+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:18:52.768+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:18:52.770+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:18:52.785+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-07-25T16:19:23.054+0000] {processor.py:154} INFO - Started process (PID=911) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:19:23.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:19:23.056+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:19:23.056+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:19:23.066+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:19:23.065+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:19:23.067+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:19:23.084+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-25T16:19:53.929+0000] {processor.py:154} INFO - Started process (PID=965) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:19:53.930+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:19:53.931+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:19:53.931+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:19:53.939+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:19:53.938+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:19:53.939+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:19:53.952+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-07-25T16:20:24.687+0000] {processor.py:154} INFO - Started process (PID=1029) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:20:24.689+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:20:24.690+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:20:24.689+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:20:24.702+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:20:24.700+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:20:24.703+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:20:24.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-07-25T16:20:55.658+0000] {processor.py:154} INFO - Started process (PID=1093) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:20:55.659+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:20:55.660+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:20:55.660+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:20:55.671+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:20:55.670+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:20:55.671+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:20:55.693+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-25T16:21:26.462+0000] {processor.py:154} INFO - Started process (PID=1157) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:21:26.464+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:21:26.464+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:21:26.464+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:21:26.474+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:21:26.473+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:21:26.475+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:21:26.494+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-25T16:21:57.360+0000] {processor.py:154} INFO - Started process (PID=1221) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:21:57.361+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:21:57.362+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:21:57.362+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:21:57.372+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:21:57.371+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:21:57.373+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:21:57.390+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-25T16:22:28.150+0000] {processor.py:154} INFO - Started process (PID=1285) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:22:28.151+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:22:28.152+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:22:28.152+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:22:28.163+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:22:28.161+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:22:28.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:22:28.180+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-25T16:22:58.836+0000] {processor.py:154} INFO - Started process (PID=1349) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:22:58.837+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:22:58.838+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:22:58.838+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:22:58.852+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:22:58.850+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:22:58.852+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:22:58.868+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-25T16:23:29.614+0000] {processor.py:154} INFO - Started process (PID=1412) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:23:29.615+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:23:29.616+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:23:29.616+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:23:29.630+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:23:29.628+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:23:29.630+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:23:29.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-25T16:24:00.399+0000] {processor.py:154} INFO - Started process (PID=1476) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:24:00.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:24:00.401+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:24:00.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:24:00.406+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:24:00.406+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:24:00.407+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:24:00.420+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-07-25T16:24:31.048+0000] {processor.py:154} INFO - Started process (PID=1531) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:24:31.050+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:24:31.051+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:24:31.051+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:24:31.064+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:24:31.063+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:24:31.065+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:24:31.084+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-25T16:25:01.678+0000] {processor.py:154} INFO - Started process (PID=1595) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:25:01.679+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:25:01.679+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:25:01.679+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:25:01.685+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:25:01.684+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:25:01.685+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:25:01.697+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2024-07-25T16:25:32.541+0000] {processor.py:154} INFO - Started process (PID=1659) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:25:32.543+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:25:32.544+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:25:32.543+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:25:32.554+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:25:32.553+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:25:32.555+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:25:32.578+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-25T16:26:03.403+0000] {processor.py:154} INFO - Started process (PID=1722) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:26:03.405+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:26:03.406+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:26:03.406+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:26:03.415+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:26:03.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:26:03.416+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:26:03.431+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-25T16:26:33.908+0000] {processor.py:154} INFO - Started process (PID=1786) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:26:33.910+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:26:33.911+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:26:33.911+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:26:33.924+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:26:33.922+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:26:33.924+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:26:33.944+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-25T16:27:04.166+0000] {processor.py:154} INFO - Started process (PID=1841) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:27:04.167+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:27:04.168+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:27:04.168+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:27:04.174+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:27:04.173+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:27:04.174+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:27:04.190+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-07-25T16:27:34.373+0000] {processor.py:154} INFO - Started process (PID=1905) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:27:34.374+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:27:34.374+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:27:34.374+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:27:34.379+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:27:34.379+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:27:34.380+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:27:34.393+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-07-25T16:28:04.624+0000] {processor.py:154} INFO - Started process (PID=1969) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:28:04.625+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:28:04.626+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:28:04.626+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:28:04.634+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:28:04.633+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:28:04.635+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:28:04.670+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-07-25T16:28:35.419+0000] {processor.py:154} INFO - Started process (PID=2033) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:28:35.420+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:28:35.420+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:28:35.420+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:28:35.427+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:28:35.426+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:28:35.427+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:28:35.441+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-07-25T16:29:05.588+0000] {processor.py:154} INFO - Started process (PID=2096) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:29:05.588+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:29:05.589+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:29:05.589+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:29:05.594+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:29:05.593+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:29:05.594+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:29:05.606+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2024-07-25T16:29:36.281+0000] {processor.py:154} INFO - Started process (PID=2150) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:29:36.282+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:29:36.283+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:29:36.283+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:29:36.295+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:29:36.293+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:29:36.295+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:29:36.314+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-25T16:30:06.915+0000] {processor.py:154} INFO - Started process (PID=2214) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:30:06.917+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:30:06.917+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:30:06.917+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:30:06.926+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:30:06.925+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:30:06.928+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:30:06.946+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-25T16:30:37.626+0000] {processor.py:154} INFO - Started process (PID=2278) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:30:37.627+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:30:37.628+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:30:37.628+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:30:37.637+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:30:37.636+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:30:37.638+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:30:37.657+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-25T16:31:08.179+0000] {processor.py:154} INFO - Started process (PID=2342) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:31:08.179+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:31:08.180+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:31:08.180+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:31:08.185+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:31:08.185+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:31:08.186+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:31:08.197+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2024-07-25T16:31:38.899+0000] {processor.py:154} INFO - Started process (PID=2406) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:31:38.902+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:31:38.903+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:31:38.903+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:31:38.913+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:31:38.911+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:31:38.913+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:31:38.931+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-25T16:40:51.379+0000] {processor.py:154} INFO - Started process (PID=2412) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:40:51.380+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:40:51.381+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:40:51.381+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:40:51.392+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:40:51.391+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:40:51.392+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:40:51.414+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-07-25T16:41:34.141+0000] {processor.py:154} INFO - Started process (PID=2476) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:41:34.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:41:34.143+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:41:34.143+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:41:34.153+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:41:34.152+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:41:34.153+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:41:34.169+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-25T16:42:05.201+0000] {processor.py:154} INFO - Started process (PID=2540) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:42:05.202+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:42:05.203+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:42:05.203+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:42:05.218+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:42:05.217+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:42:05.218+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:42:05.242+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-07-25T16:52:17.093+0000] {processor.py:154} INFO - Started process (PID=2604) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:52:17.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:52:17.094+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:52:17.094+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:52:17.110+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:52:17.106+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:52:17.110+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:52:17.132+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-25T16:52:47.661+0000] {processor.py:154} INFO - Started process (PID=2659) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:52:47.663+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:52:47.665+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:52:47.665+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:52:47.682+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:52:47.676+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:52:47.682+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:52:47.705+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-07-25T16:53:18.690+0000] {processor.py:154} INFO - Started process (PID=2723) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:53:18.692+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:53:18.693+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:53:18.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:53:18.705+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:53:18.704+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:53:18.705+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:53:18.727+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-25T16:53:48.816+0000] {processor.py:154} INFO - Started process (PID=2786) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:53:48.818+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:53:48.818+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:53:48.818+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:53:48.827+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:53:48.827+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:53:48.828+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:53:48.844+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-25T16:54:19.836+0000] {processor.py:154} INFO - Started process (PID=2850) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:54:19.837+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:54:19.838+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:54:19.838+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:54:19.849+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:54:19.848+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:54:19.850+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:54:19.863+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-25T16:54:49.881+0000] {processor.py:154} INFO - Started process (PID=2914) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:54:49.882+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:54:49.882+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:54:49.882+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:54:49.889+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:54:49.888+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:54:49.889+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:54:49.900+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.022 seconds
[2024-07-25T16:55:20.706+0000] {processor.py:154} INFO - Started process (PID=2977) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:55:20.706+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:55:20.707+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:55:20.707+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:55:20.713+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:55:20.712+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:55:20.713+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:55:20.724+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.022 seconds
[2024-07-25T16:55:50.762+0000] {processor.py:154} INFO - Started process (PID=3032) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:55:50.764+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:55:50.765+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:55:50.765+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:55:50.775+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:55:50.774+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:55:50.775+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:55:50.790+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-25T16:56:20.977+0000] {processor.py:154} INFO - Started process (PID=3096) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:56:20.978+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:56:20.979+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:56:20.979+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:56:20.989+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:56:20.987+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:56:20.989+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:56:21.007+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-25T16:56:51.915+0000] {processor.py:154} INFO - Started process (PID=3160) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:56:51.917+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:56:51.918+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:56:51.918+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:56:51.929+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:56:51.928+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:56:51.930+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:56:51.949+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-07-25T16:57:22.724+0000] {processor.py:154} INFO - Started process (PID=3224) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:57:22.726+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:57:22.726+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:57:22.726+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:57:22.736+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:57:22.735+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:57:22.736+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:57:22.755+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-25T16:57:53.584+0000] {processor.py:154} INFO - Started process (PID=3287) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:57:53.585+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:57:53.585+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:57:53.585+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:57:53.590+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:57:53.589+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:57:53.591+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:57:53.600+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.017 seconds
[2024-07-25T16:58:24.411+0000] {processor.py:154} INFO - Started process (PID=3350) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:58:24.412+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:58:24.414+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:58:24.413+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:58:24.423+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:58:24.422+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:58:24.423+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:58:24.441+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-25T16:58:55.282+0000] {processor.py:154} INFO - Started process (PID=3414) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:58:55.283+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:58:55.284+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:58:55.283+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:58:55.293+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:58:55.292+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:58:55.293+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:58:55.312+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-25T16:59:26.292+0000] {processor.py:154} INFO - Started process (PID=3467) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T16:59:26.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T16:59:26.295+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:59:26.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T16:59:26.303+0000] {logging_mixin.py:120} INFO - [2024-07-25T16:59:26.302+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T16:59:26.303+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T16:59:26.317+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-07-25T17:36:22.521+0000] {processor.py:154} INFO - Started process (PID=3531) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T17:36:22.526+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T17:36:22.527+0000] {logging_mixin.py:120} INFO - [2024-07-25T17:36:22.527+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T17:36:22.544+0000] {logging_mixin.py:120} INFO - [2024-07-25T17:36:22.541+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T17:36:22.545+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T17:36:22.622+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.109 seconds
[2024-07-25T18:03:42.027+0000] {processor.py:154} INFO - Started process (PID=3586) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T18:03:42.028+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T18:03:42.029+0000] {logging_mixin.py:120} INFO - [2024-07-25T18:03:42.029+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T18:03:42.042+0000] {logging_mixin.py:120} INFO - [2024-07-25T18:03:42.041+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T18:03:42.042+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T18:03:42.064+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-25T18:31:46.459+0000] {processor.py:154} INFO - Started process (PID=3650) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T18:31:46.461+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T18:31:46.465+0000] {logging_mixin.py:120} INFO - [2024-07-25T18:31:46.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T18:31:46.536+0000] {logging_mixin.py:120} INFO - [2024-07-25T18:31:46.526+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T18:31:46.549+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T18:31:46.584+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.137 seconds
[2024-07-25T19:12:30.055+0000] {processor.py:154} INFO - Started process (PID=3714) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T19:12:30.061+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T19:12:30.063+0000] {logging_mixin.py:120} INFO - [2024-07-25T19:12:30.062+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T19:12:30.097+0000] {logging_mixin.py:120} INFO - [2024-07-25T19:12:30.086+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T19:12:30.106+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T19:12:30.149+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.103 seconds
[2024-07-25T19:53:12.047+0000] {processor.py:154} INFO - Started process (PID=3777) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T19:53:12.048+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T19:53:12.049+0000] {logging_mixin.py:120} INFO - [2024-07-25T19:53:12.049+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T19:53:12.070+0000] {logging_mixin.py:120} INFO - [2024-07-25T19:53:12.067+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T19:53:12.073+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T19:53:12.088+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-07-25T20:27:15.678+0000] {processor.py:154} INFO - Started process (PID=3841) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T20:27:15.697+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T20:27:15.700+0000] {logging_mixin.py:120} INFO - [2024-07-25T20:27:15.700+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T20:27:15.722+0000] {logging_mixin.py:120} INFO - [2024-07-25T20:27:15.721+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T20:27:15.723+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T20:27:15.749+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.083 seconds
[2024-07-25T21:02:11.190+0000] {processor.py:154} INFO - Started process (PID=3896) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T21:02:11.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T21:02:11.194+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:02:11.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T21:02:11.206+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:02:11.204+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T21:02:11.206+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T21:02:11.232+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-07-25T21:03:13.535+0000] {processor.py:154} INFO - Started process (PID=3960) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T21:03:13.536+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T21:03:13.537+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:03:13.537+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T21:03:13.554+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:03:13.553+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T21:03:13.554+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T21:03:13.570+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-07-25T21:49:00.340+0000] {processor.py:154} INFO - Started process (PID=4024) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T21:49:00.341+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T21:49:00.342+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:49:00.342+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T21:49:00.362+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:49:00.360+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T21:49:00.363+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T21:49:00.399+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2024-07-25T21:50:28.414+0000] {processor.py:154} INFO - Started process (PID=4088) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T21:50:28.416+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T21:50:28.417+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:50:28.417+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T21:50:28.436+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:50:28.432+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T21:50:28.437+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T21:50:28.457+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-07-25T21:57:38.889+0000] {processor.py:154} INFO - Started process (PID=4152) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T21:57:38.891+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T21:57:38.892+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:57:38.892+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T21:57:38.925+0000] {logging_mixin.py:120} INFO - [2024-07-25T21:57:38.918+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T21:57:38.928+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T21:57:38.972+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.094 seconds
[2024-07-25T22:03:12.370+0000] {processor.py:154} INFO - Started process (PID=4207) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:03:12.373+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:03:12.373+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:03:12.373+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:03:12.383+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:03:12.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:03:12.383+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:03:12.398+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-25T22:04:45.781+0000] {processor.py:154} INFO - Started process (PID=4270) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:04:45.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:04:45.785+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:04:45.785+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:04:45.803+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:04:45.801+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:04:45.804+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:04:45.826+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-07-25T22:06:55.566+0000] {processor.py:154} INFO - Started process (PID=4334) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:06:55.569+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:06:55.570+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:06:55.570+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:06:55.582+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:06:55.581+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:06:55.583+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:06:55.602+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-25T22:08:40.148+0000] {processor.py:154} INFO - Started process (PID=4398) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:08:40.149+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:08:40.150+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:08:40.150+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:08:40.161+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:08:40.161+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:08:40.162+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:08:40.181+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-25T22:09:39.975+0000] {processor.py:154} INFO - Started process (PID=4453) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:09:39.977+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:09:39.978+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:09:39.978+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:09:39.986+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:09:39.985+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:09:39.987+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:09:40.002+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-25T22:18:07.857+0000] {processor.py:154} INFO - Started process (PID=4516) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:18:07.858+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:18:07.859+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:18:07.859+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:18:07.871+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:18:07.869+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:18:07.871+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:18:07.896+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-25T22:19:01.638+0000] {processor.py:154} INFO - Started process (PID=4580) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:19:01.640+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:19:01.641+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:19:01.641+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:19:01.659+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:19:01.658+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:19:01.659+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:19:01.681+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-07-25T22:56:32.544+0000] {processor.py:154} INFO - Started process (PID=4643) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T22:56:32.545+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T22:56:32.546+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:56:32.546+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T22:56:32.554+0000] {logging_mixin.py:120} INFO - [2024-07-25T22:56:32.553+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T22:56:32.555+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T22:56:32.572+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-25T23:21:43.341+0000] {processor.py:154} INFO - Started process (PID=4706) to work on /opt/airflow/dags/test_dag.py
[2024-07-25T23:21:43.421+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-25T23:21:43.451+0000] {logging_mixin.py:120} INFO - [2024-07-25T23:21:43.451+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-25T23:21:43.525+0000] {logging_mixin.py:120} INFO - [2024-07-25T23:21:43.523+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-25T23:21:43.526+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-25T23:21:43.559+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.229 seconds
