[2024-07-26T00:02:52.756+0000] {processor.py:154} INFO - Started process (PID=4761) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T00:02:52.758+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T00:02:52.760+0000] {logging_mixin.py:120} INFO - [2024-07-26T00:02:52.760+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T00:02:52.791+0000] {logging_mixin.py:120} INFO - [2024-07-26T00:02:52.785+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T00:02:52.793+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T00:02:52.844+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.102 seconds
[2024-07-26T00:16:05.827+0000] {processor.py:154} INFO - Started process (PID=4825) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T00:16:05.827+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T00:16:05.828+0000] {logging_mixin.py:120} INFO - [2024-07-26T00:16:05.828+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T00:16:05.842+0000] {logging_mixin.py:120} INFO - [2024-07-26T00:16:05.841+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T00:16:05.842+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T00:16:05.865+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-26T00:40:51.212+0000] {processor.py:154} INFO - Started process (PID=4889) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T00:40:51.215+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T00:40:51.216+0000] {logging_mixin.py:120} INFO - [2024-07-26T00:40:51.216+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T00:40:51.231+0000] {logging_mixin.py:120} INFO - [2024-07-26T00:40:51.229+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T00:40:51.232+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T00:40:51.270+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2024-07-26T01:30:31.985+0000] {processor.py:154} INFO - Started process (PID=4953) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T01:30:31.986+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T01:30:31.987+0000] {logging_mixin.py:120} INFO - [2024-07-26T01:30:31.987+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T01:30:32.000+0000] {logging_mixin.py:120} INFO - [2024-07-26T01:30:31.999+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T01:30:32.001+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T01:30:32.017+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-26T02:00:27.967+0000] {processor.py:154} INFO - Started process (PID=5017) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T02:00:27.981+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T02:00:27.990+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:00:27.990+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T02:00:28.024+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:00:28.021+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T02:00:28.029+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T02:00:28.075+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.125 seconds
[2024-07-26T02:12:59.826+0000] {processor.py:154} INFO - Started process (PID=5072) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T02:12:59.827+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T02:12:59.828+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:12:59.828+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T02:12:59.843+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:12:59.839+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T02:12:59.843+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T02:12:59.860+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-07-26T02:39:10.738+0000] {processor.py:154} INFO - Started process (PID=5135) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T02:39:10.739+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T02:39:10.740+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:39:10.740+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T02:39:10.759+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:39:10.757+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T02:39:10.760+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T02:39:10.795+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-07-26T02:58:10.678+0000] {processor.py:154} INFO - Started process (PID=5199) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T02:58:10.679+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T02:58:10.680+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:58:10.680+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T02:58:10.696+0000] {logging_mixin.py:120} INFO - [2024-07-26T02:58:10.691+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T02:58:10.697+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T02:58:10.721+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-07-26T03:01:33.028+0000] {processor.py:154} INFO - Started process (PID=5263) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T03:01:33.031+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T03:01:33.042+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:01:33.042+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T03:01:33.074+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:01:33.070+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T03:01:33.078+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T03:01:33.149+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.132 seconds
[2024-07-26T03:15:38.900+0000] {processor.py:154} INFO - Started process (PID=5318) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T03:15:38.903+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T03:15:38.906+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:15:38.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T03:15:38.934+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:15:38.932+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T03:15:38.934+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T03:15:38.975+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2024-07-26T03:32:14.716+0000] {processor.py:154} INFO - Started process (PID=5382) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T03:32:14.718+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T03:32:14.719+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:32:14.719+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T03:32:14.746+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:32:14.743+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T03:32:14.751+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T03:32:14.797+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.085 seconds
[2024-07-26T03:56:56.971+0000] {processor.py:154} INFO - Started process (PID=5446) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T03:56:56.972+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T03:56:56.973+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:56:56.973+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T03:56:56.988+0000] {logging_mixin.py:120} INFO - [2024-07-26T03:56:56.987+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T03:56:56.989+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T03:56:57.004+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-26T04:02:03.135+0000] {processor.py:154} INFO - Started process (PID=5510) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:02:03.141+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:02:03.152+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:02:03.152+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:02:03.176+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:02:03.168+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:02:03.177+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:02:03.211+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.081 seconds
[2024-07-26T04:04:15.576+0000] {processor.py:154} INFO - Started process (PID=5574) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:04:15.577+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:04:15.578+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:04:15.578+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:04:15.590+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:04:15.589+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:04:15.591+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:04:15.613+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-26T04:06:02.814+0000] {processor.py:154} INFO - Started process (PID=5628) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:06:02.816+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:06:02.817+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:06:02.817+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:06:02.839+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:06:02.832+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:06:02.839+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:06:02.868+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-07-26T04:08:04.736+0000] {processor.py:154} INFO - Started process (PID=5692) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:08:04.737+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:08:04.738+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:08:04.737+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:08:04.747+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:08:04.746+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:08:04.747+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:08:04.764+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-26T04:09:00.767+0000] {processor.py:154} INFO - Started process (PID=5756) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:09:00.768+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:09:00.769+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:09:00.769+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:09:00.780+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:09:00.779+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:09:00.780+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:09:00.796+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-26T04:10:10.339+0000] {processor.py:154} INFO - Started process (PID=5821) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:10:10.341+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:10:10.342+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:10:10.342+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:10:10.359+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:10:10.358+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:10:10.360+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:10:10.384+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-07-26T04:11:36.640+0000] {processor.py:154} INFO - Started process (PID=5885) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:11:36.641+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:11:36.643+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:11:36.643+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:11:36.657+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:11:36.656+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:11:36.658+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:11:36.677+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-26T04:12:20.287+0000] {processor.py:154} INFO - Started process (PID=5940) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:12:20.288+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:12:20.289+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:12:20.289+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:12:20.305+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:12:20.301+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:12:20.305+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:12:20.327+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-07-26T04:13:13.507+0000] {processor.py:154} INFO - Started process (PID=6004) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:13:13.508+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:13:13.509+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:13:13.509+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:13:13.518+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:13:13.517+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:13:13.518+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:13:13.534+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-26T04:14:03.984+0000] {processor.py:154} INFO - Started process (PID=6067) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:14:03.985+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:14:03.986+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:14:03.986+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:14:04.000+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:14:03.999+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:14:04.000+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:14:04.020+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-26T04:18:31.701+0000] {processor.py:154} INFO - Started process (PID=6131) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:18:31.702+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:18:31.704+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:18:31.704+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:18:31.730+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:18:31.728+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:18:31.732+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:18:31.813+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.126 seconds
[2024-07-26T04:19:15.167+0000] {processor.py:154} INFO - Started process (PID=6195) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:19:15.168+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:19:15.170+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:19:15.169+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:19:15.186+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:19:15.182+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:19:15.186+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:19:15.215+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-07-26T04:20:36.846+0000] {processor.py:154} INFO - Started process (PID=6250) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:20:36.848+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:20:36.849+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:20:36.849+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:20:36.864+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:20:36.863+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:20:36.865+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:20:36.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-07-26T04:21:40.865+0000] {processor.py:154} INFO - Started process (PID=6313) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:21:40.867+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:21:40.868+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:21:40.868+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:21:40.887+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:21:40.886+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:21:40.890+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:21:40.911+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-07-26T04:22:47.217+0000] {processor.py:154} INFO - Started process (PID=6377) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:22:47.218+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:22:47.219+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:22:47.219+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:22:47.230+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:22:47.229+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:22:47.231+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:22:47.249+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-26T04:33:59.753+0000] {processor.py:154} INFO - Started process (PID=6441) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:33:59.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:33:59.754+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:33:59.754+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:33:59.763+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:33:59.762+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:33:59.763+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:33:59.776+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-07-26T04:49:11.865+0000] {processor.py:154} INFO - Started process (PID=6505) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:49:11.870+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:49:11.873+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:49:11.873+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:49:11.901+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:49:11.894+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:49:11.905+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:49:11.985+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.124 seconds
[2024-07-26T04:53:36.772+0000] {processor.py:154} INFO - Started process (PID=6560) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T04:53:36.775+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T04:53:36.776+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:53:36.776+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T04:53:36.786+0000] {logging_mixin.py:120} INFO - [2024-07-26T04:53:36.785+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T04:53:36.787+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T04:53:36.805+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-26T05:02:48.903+0000] {processor.py:154} INFO - Started process (PID=6624) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T05:02:48.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T05:02:48.906+0000] {logging_mixin.py:120} INFO - [2024-07-26T05:02:48.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T05:02:48.934+0000] {logging_mixin.py:120} INFO - [2024-07-26T05:02:48.931+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T05:02:48.935+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T05:02:48.960+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-07-26T05:15:51.240+0000] {processor.py:154} INFO - Started process (PID=6688) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T05:15:51.242+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T05:15:51.242+0000] {logging_mixin.py:120} INFO - [2024-07-26T05:15:51.242+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T05:15:51.252+0000] {logging_mixin.py:120} INFO - [2024-07-26T05:15:51.251+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T05:15:51.252+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T05:15:51.267+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-26T05:33:28.034+0000] {processor.py:154} INFO - Started process (PID=6752) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T05:33:28.036+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T05:33:28.036+0000] {logging_mixin.py:120} INFO - [2024-07-26T05:33:28.036+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T05:33:28.056+0000] {logging_mixin.py:120} INFO - [2024-07-26T05:33:28.053+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T05:33:28.057+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T05:33:28.077+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-07-26T06:09:34.937+0000] {processor.py:154} INFO - Started process (PID=6807) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T06:09:34.948+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T06:09:34.949+0000] {logging_mixin.py:120} INFO - [2024-07-26T06:09:34.949+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T06:09:35.013+0000] {logging_mixin.py:120} INFO - [2024-07-26T06:09:34.989+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T06:09:35.016+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T06:09:35.094+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.173 seconds
[2024-07-26T07:10:32.276+0000] {processor.py:154} INFO - Started process (PID=6870) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T07:10:32.279+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T07:10:32.280+0000] {logging_mixin.py:120} INFO - [2024-07-26T07:10:32.280+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T07:10:32.293+0000] {logging_mixin.py:120} INFO - [2024-07-26T07:10:32.292+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T07:10:32.294+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T07:10:32.319+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.051 seconds
[2024-07-26T08:11:46.462+0000] {processor.py:154} INFO - Started process (PID=6934) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T08:11:46.466+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T08:11:46.468+0000] {logging_mixin.py:120} INFO - [2024-07-26T08:11:46.468+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T08:11:46.498+0000] {logging_mixin.py:120} INFO - [2024-07-26T08:11:46.496+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T08:11:46.499+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T08:11:46.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.107 seconds
[2024-07-26T08:36:10.472+0000] {processor.py:154} INFO - Started process (PID=6998) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T08:36:10.475+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T08:36:10.476+0000] {logging_mixin.py:120} INFO - [2024-07-26T08:36:10.476+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T08:36:10.516+0000] {logging_mixin.py:120} INFO - [2024-07-26T08:36:10.504+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T08:36:10.518+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T08:36:10.577+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.117 seconds
[2024-07-26T09:29:24.799+0000] {processor.py:154} INFO - Started process (PID=7062) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T09:29:24.823+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T09:29:24.832+0000] {logging_mixin.py:120} INFO - [2024-07-26T09:29:24.832+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T09:29:24.930+0000] {logging_mixin.py:120} INFO - [2024-07-26T09:29:24.926+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T09:29:24.937+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T09:29:25.114+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.325 seconds
[2024-07-26T10:30:29.535+0000] {processor.py:154} INFO - Started process (PID=7117) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T10:30:29.539+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T10:30:29.540+0000] {logging_mixin.py:120} INFO - [2024-07-26T10:30:29.540+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T10:30:29.572+0000] {logging_mixin.py:120} INFO - [2024-07-26T10:30:29.558+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T10:30:29.573+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T10:30:29.648+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.143 seconds
[2024-07-26T10:39:55.563+0000] {processor.py:154} INFO - Started process (PID=7181) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T10:39:55.564+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T10:39:55.565+0000] {logging_mixin.py:120} INFO - [2024-07-26T10:39:55.565+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T10:39:55.582+0000] {logging_mixin.py:120} INFO - [2024-07-26T10:39:55.581+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T10:39:55.583+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T10:39:55.609+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-07-26T11:48:29.686+0000] {processor.py:154} INFO - Started process (PID=7245) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T11:48:29.701+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T11:48:29.704+0000] {logging_mixin.py:120} INFO - [2024-07-26T11:48:29.704+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T11:48:29.726+0000] {logging_mixin.py:120} INFO - [2024-07-26T11:48:29.724+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T11:48:29.728+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T11:48:29.756+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.087 seconds
[2024-07-26T12:13:04.988+0000] {processor.py:154} INFO - Started process (PID=7309) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T12:13:04.989+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T12:13:04.991+0000] {logging_mixin.py:120} INFO - [2024-07-26T12:13:04.991+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T12:13:05.004+0000] {logging_mixin.py:120} INFO - [2024-07-26T12:13:05.003+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T12:13:05.005+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T12:13:05.027+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-26T12:19:24.992+0000] {processor.py:154} INFO - Started process (PID=7364) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T12:19:24.993+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T12:19:24.994+0000] {logging_mixin.py:120} INFO - [2024-07-26T12:19:24.994+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T12:19:25.007+0000] {logging_mixin.py:120} INFO - [2024-07-26T12:19:25.006+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T12:19:25.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T12:19:25.032+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-26T13:00:06.134+0000] {processor.py:154} INFO - Started process (PID=7427) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:00:06.138+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:00:06.151+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:00:06.151+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:00:06.219+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:00:06.210+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:00:06.225+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:00:06.283+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.152 seconds
[2024-07-26T13:12:26.633+0000] {processor.py:154} INFO - Started process (PID=7491) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:12:26.637+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:12:26.645+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:12:26.645+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:12:26.683+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:12:26.680+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:12:26.684+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:12:26.768+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.144 seconds
[2024-07-26T13:43:20.689+0000] {processor.py:154} INFO - Started process (PID=7555) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:43:20.691+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:43:20.694+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:43:20.693+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:43:20.725+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:43:20.716+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:43:20.730+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:43:20.784+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.102 seconds
[2024-07-26T13:46:52.376+0000] {processor.py:154} INFO - Started process (PID=7619) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:46:52.388+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:46:52.393+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:46:52.392+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:46:52.518+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:46:52.496+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:46:52.530+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:46:52.628+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.275 seconds
[2024-07-26T13:52:21.556+0000] {processor.py:154} INFO - Started process (PID=7674) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:52:21.558+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:52:21.558+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:52:21.558+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:52:21.576+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:52:21.574+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:52:21.577+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:52:21.605+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-07-26T13:54:20.585+0000] {processor.py:154} INFO - Started process (PID=7738) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:54:20.587+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:54:20.588+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:54:20.587+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:54:20.602+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:54:20.601+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:54:20.602+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:54:20.626+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-07-26T13:55:28.583+0000] {processor.py:154} INFO - Started process (PID=7802) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T13:55:28.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T13:55:28.591+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:55:28.591+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T13:55:28.606+0000] {logging_mixin.py:120} INFO - [2024-07-26T13:55:28.604+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T13:55:28.607+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T13:55:28.700+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.121 seconds
[2024-07-26T14:05:30.065+0000] {processor.py:154} INFO - Started process (PID=7866) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T14:05:30.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T14:05:30.066+0000] {logging_mixin.py:120} INFO - [2024-07-26T14:05:30.066+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T14:05:30.076+0000] {logging_mixin.py:120} INFO - [2024-07-26T14:05:30.075+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T14:05:30.076+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T14:05:30.094+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-26T14:06:19.489+0000] {processor.py:154} INFO - Started process (PID=7920) to work on /opt/airflow/dags/test_dag.py
[2024-07-26T14:06:19.493+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-26T14:06:19.494+0000] {logging_mixin.py:120} INFO - [2024-07-26T14:06:19.494+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-26T14:06:19.515+0000] {logging_mixin.py:120} INFO - [2024-07-26T14:06:19.513+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-26T14:06:19.515+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-26T14:06:19.543+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
