[2024-07-24T20:21:11.627+0000] {processor.py:154} INFO - Started process (PID=36) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:21:11.630+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:21:11.630+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:21:11.630+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:21:11.648+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:21:11.647+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:21:11.649+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:21:11.683+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-07-24T20:21:42.580+0000] {processor.py:154} INFO - Started process (PID=100) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:21:42.582+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:21:42.583+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:21:42.583+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:21:42.594+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:21:42.593+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:21:42.594+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:21:42.607+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:22:13.251+0000] {processor.py:154} INFO - Started process (PID=164) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:22:13.253+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:22:13.253+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:22:13.253+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:22:13.269+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:22:13.268+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:22:13.269+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:22:13.297+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-07-24T20:22:38.152+0000] {processor.py:154} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:22:38.155+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:22:38.157+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:22:38.157+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:22:38.178+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:22:38.174+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:22:38.178+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:22:38.197+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-07-24T20:23:08.491+0000] {processor.py:154} INFO - Started process (PID=101) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:23:08.495+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:23:08.496+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:23:08.496+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:23:08.510+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:23:08.509+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:23:08.510+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:23:08.529+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-24T20:23:39.394+0000] {processor.py:154} INFO - Started process (PID=166) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:23:39.397+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:23:39.398+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:23:39.398+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:23:39.418+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:23:39.416+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:23:39.419+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:23:39.443+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-07-24T20:24:10.347+0000] {processor.py:154} INFO - Started process (PID=230) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:24:10.348+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:24:10.349+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:24:10.349+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:24:10.358+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:24:10.357+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:24:10.359+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:24:10.372+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-07-24T20:24:41.273+0000] {processor.py:154} INFO - Started process (PID=285) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:24:41.274+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:24:41.275+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:24:41.275+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:24:41.289+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:24:41.288+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:24:41.290+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:24:41.307+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-24T20:25:11.417+0000] {processor.py:154} INFO - Started process (PID=349) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:25:11.419+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:25:11.420+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:25:11.419+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:25:11.438+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:25:11.437+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:25:11.439+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:25:11.455+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-24T20:25:41.573+0000] {processor.py:154} INFO - Started process (PID=413) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:25:41.574+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:25:41.575+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:25:41.575+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:25:41.584+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:25:41.583+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:25:41.585+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:25:41.600+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-24T20:26:11.664+0000] {processor.py:154} INFO - Started process (PID=477) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:26:11.666+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:26:11.667+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:26:11.667+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:26:11.678+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:26:11.677+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:26:11.679+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:26:11.700+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-07-24T20:26:42.533+0000] {processor.py:154} INFO - Started process (PID=541) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:26:42.535+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:26:42.535+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:26:42.535+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:26:42.546+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:26:42.545+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:26:42.547+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:26:42.560+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:27:13.328+0000] {processor.py:154} INFO - Started process (PID=605) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:27:13.329+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:27:13.329+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:27:13.329+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:27:13.342+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:27:13.341+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:27:13.343+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:27:13.355+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.028 seconds
[2024-07-24T20:27:44.068+0000] {processor.py:154} INFO - Started process (PID=669) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:27:44.069+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:27:44.070+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:27:44.070+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:27:44.082+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:27:44.081+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:27:44.083+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:27:44.094+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-24T20:28:14.950+0000] {processor.py:154} INFO - Started process (PID=724) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:28:14.951+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:28:14.952+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:28:14.952+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:28:14.962+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:28:14.961+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:28:14.963+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:28:14.975+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-24T20:28:45.903+0000] {processor.py:154} INFO - Started process (PID=788) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:28:45.905+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:28:45.906+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:28:45.906+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:28:45.917+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:28:45.916+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:28:45.918+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:28:45.932+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-24T20:29:16.820+0000] {processor.py:154} INFO - Started process (PID=852) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:29:16.821+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:29:16.821+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:29:16.821+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:29:16.830+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:29:16.829+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:29:16.830+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:29:16.846+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-24T20:29:47.623+0000] {processor.py:154} INFO - Started process (PID=916) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:29:47.624+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:29:47.625+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:29:47.625+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:29:47.646+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:29:47.643+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:29:47.647+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:29:47.666+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-07-24T20:30:18.464+0000] {processor.py:154} INFO - Started process (PID=980) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:30:18.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:30:18.466+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:30:18.466+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:30:18.480+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:30:18.479+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:30:18.480+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:30:18.495+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-24T20:30:49.298+0000] {processor.py:154} INFO - Started process (PID=1044) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:30:49.300+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:30:49.301+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:30:49.301+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:30:49.317+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:30:49.316+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:30:49.319+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:30:49.336+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-24T20:31:20.170+0000] {processor.py:154} INFO - Started process (PID=1108) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:31:20.172+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:31:20.173+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:31:20.173+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:31:20.192+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:31:20.191+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:31:20.193+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:31:20.208+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-24T20:31:51.064+0000] {processor.py:154} INFO - Started process (PID=1171) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:31:51.065+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:31:51.065+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:31:51.065+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:31:51.078+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:31:51.077+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:31:51.078+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:31:51.090+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-07-24T20:32:22.032+0000] {processor.py:154} INFO - Started process (PID=1235) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:32:22.033+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:32:22.034+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:32:22.034+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:32:22.043+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:32:22.042+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:32:22.043+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:32:22.060+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:32:52.932+0000] {processor.py:154} INFO - Started process (PID=1299) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:32:52.932+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:32:52.933+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:32:52.933+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:32:52.940+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:32:52.939+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:32:52.940+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:32:52.953+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.024 seconds
[2024-07-24T20:33:23.823+0000] {processor.py:154} INFO - Started process (PID=1354) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:33:23.824+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:33:23.824+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:33:23.824+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:33:23.833+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:33:23.832+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:33:23.833+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:33:23.846+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-24T20:33:54.704+0000] {processor.py:154} INFO - Started process (PID=1417) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:33:54.706+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:33:54.707+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:33:54.707+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:33:54.715+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:33:54.714+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:33:54.715+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:33:54.729+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-24T20:34:25.563+0000] {processor.py:154} INFO - Started process (PID=1481) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:34:25.565+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:34:25.565+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:34:25.565+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:34:25.580+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:34:25.579+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:34:25.581+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:34:25.594+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-24T20:34:56.189+0000] {processor.py:154} INFO - Started process (PID=1545) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:34:56.191+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:34:56.192+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:34:56.192+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:34:56.201+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:34:56.200+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:34:56.202+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:34:56.216+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:35:26.813+0000] {processor.py:154} INFO - Started process (PID=1609) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:35:26.814+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:35:26.815+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:35:26.815+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:35:26.825+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:35:26.823+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:35:26.825+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:35:26.839+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:35:57.489+0000] {processor.py:154} INFO - Started process (PID=1673) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:35:57.491+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:35:57.492+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:35:57.492+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:35:57.501+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:35:57.500+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:35:57.502+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:35:57.515+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:36:28.138+0000] {processor.py:154} INFO - Started process (PID=1737) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:36:28.140+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:36:28.140+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:36:28.140+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:36:28.151+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:36:28.150+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:36:28.151+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:36:28.164+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-24T20:36:58.862+0000] {processor.py:154} INFO - Started process (PID=1801) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:36:58.864+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:36:58.866+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:36:58.865+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:36:58.878+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:36:58.876+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:36:58.879+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:36:58.895+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-07-24T20:37:29.499+0000] {processor.py:154} INFO - Started process (PID=1856) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:37:29.500+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:37:29.501+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:37:29.501+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:37:29.510+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:37:29.509+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:37:29.510+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:37:29.523+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-07-24T20:38:00.307+0000] {processor.py:154} INFO - Started process (PID=1920) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:38:00.308+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:38:00.309+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:38:00.309+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:38:00.320+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:38:00.319+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:38:00.321+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:38:00.336+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:38:30.972+0000] {processor.py:154} INFO - Started process (PID=1983) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:38:30.973+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:38:30.974+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:38:30.974+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:38:30.981+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:38:30.980+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:38:30.981+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:38:30.995+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-07-24T20:39:01.581+0000] {processor.py:154} INFO - Started process (PID=2046) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:39:01.582+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:39:01.584+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:39:01.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:39:01.593+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:39:01.592+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:39:01.594+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:39:01.609+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:39:32.232+0000] {processor.py:154} INFO - Started process (PID=2110) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:39:32.233+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:39:32.234+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:39:32.234+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:39:32.238+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:39:32.237+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:39:32.238+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:39:32.250+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.019 seconds
[2024-07-24T20:40:02.784+0000] {processor.py:154} INFO - Started process (PID=2174) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:40:02.785+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:40:02.786+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:40:02.786+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:40:02.794+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:40:02.793+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:40:02.795+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:40:02.808+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.026 seconds
[2024-07-24T20:40:33.560+0000] {processor.py:154} INFO - Started process (PID=2238) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:40:33.562+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:40:33.562+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:40:33.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:40:33.571+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:40:33.570+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:40:33.572+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:40:33.583+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.025 seconds
[2024-07-24T20:41:04.287+0000] {processor.py:154} INFO - Started process (PID=2302) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:41:04.288+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:41:04.289+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:41:04.289+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:41:04.300+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:41:04.299+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:41:04.301+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:41:04.314+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:41:35.045+0000] {processor.py:154} INFO - Started process (PID=2357) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:41:35.047+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:41:35.048+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:41:35.048+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:41:35.057+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:41:35.056+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:41:35.057+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:41:35.070+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-24T20:42:05.766+0000] {processor.py:154} INFO - Started process (PID=2420) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:42:05.768+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:42:05.769+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:42:05.768+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:42:05.782+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:42:05.779+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:42:05.782+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:42:05.796+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-24T20:42:36.545+0000] {processor.py:154} INFO - Started process (PID=2484) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:42:36.546+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:42:36.548+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:42:36.547+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:42:36.556+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:42:36.555+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:42:36.557+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:42:36.571+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:43:07.402+0000] {processor.py:154} INFO - Started process (PID=2548) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:43:07.404+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:43:07.406+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:43:07.406+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:43:07.416+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:43:07.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:43:07.416+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:43:07.430+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:43:38.089+0000] {processor.py:154} INFO - Started process (PID=2612) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:43:38.090+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:43:38.091+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:43:38.090+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:43:38.096+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:43:38.096+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:43:38.097+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:43:38.109+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.023 seconds
[2024-07-24T20:44:08.895+0000] {processor.py:154} INFO - Started process (PID=2676) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:44:08.896+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:44:08.898+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:44:08.898+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:44:08.912+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:44:08.909+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:44:08.912+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:44:08.926+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-24T20:44:39.591+0000] {processor.py:154} INFO - Started process (PID=2740) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:44:39.593+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:44:39.593+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:44:39.593+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:44:39.603+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:44:39.602+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:44:39.603+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:44:39.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-24T20:45:10.439+0000] {processor.py:154} INFO - Started process (PID=2804) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:45:10.440+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:45:10.441+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:45:10.441+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:45:10.448+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:45:10.447+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:45:10.449+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:45:10.463+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-07-24T20:45:41.023+0000] {processor.py:154} INFO - Started process (PID=2868) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:45:41.024+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:45:41.024+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:45:41.024+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:45:41.029+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:45:41.029+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:45:41.030+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:45:41.041+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.020 seconds
[2024-07-24T20:46:11.717+0000] {processor.py:154} INFO - Started process (PID=2923) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:46:11.719+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:46:11.720+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:46:11.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:46:11.729+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:46:11.728+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:46:11.729+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:46:11.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.030 seconds
[2024-07-24T20:46:42.381+0000] {processor.py:154} INFO - Started process (PID=2987) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:46:42.383+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:46:42.384+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:46:42.384+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:46:42.393+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:46:42.392+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:46:42.394+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:46:42.408+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:47:13.071+0000] {processor.py:154} INFO - Started process (PID=3051) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:47:13.073+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:47:13.073+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:47:13.073+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:47:13.078+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:47:13.077+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:47:13.078+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:47:13.090+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.021 seconds
[2024-07-24T20:47:43.809+0000] {processor.py:154} INFO - Started process (PID=3115) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:47:43.811+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:47:43.812+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:47:43.812+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:47:43.830+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:47:43.828+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:47:43.831+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:47:43.848+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-07-24T20:48:14.727+0000] {processor.py:154} INFO - Started process (PID=3179) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:48:14.728+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:48:14.728+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:48:14.728+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:48:14.736+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:48:14.736+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:48:14.737+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:48:14.752+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-07-24T20:48:45.429+0000] {processor.py:154} INFO - Started process (PID=3243) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:48:45.429+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:48:45.430+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:48:45.430+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:48:45.442+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:48:45.441+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:48:45.443+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:48:45.462+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-24T20:49:16.230+0000] {processor.py:154} INFO - Started process (PID=3307) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:49:16.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:49:16.232+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:49:16.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:49:16.242+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:49:16.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:49:16.243+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:49:16.257+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.029 seconds
[2024-07-24T20:49:46.428+0000] {processor.py:154} INFO - Started process (PID=3371) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:49:46.430+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:49:46.431+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:49:46.431+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:49:46.446+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:49:46.445+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:49:46.447+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:49:46.459+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-24T20:50:17.304+0000] {processor.py:154} INFO - Started process (PID=3549) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:50:17.306+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:50:17.307+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:50:17.307+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:50:17.327+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:50:17.325+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:50:17.330+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:50:17.344+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-24T20:50:48.257+0000] {processor.py:154} INFO - Started process (PID=3613) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:50:48.258+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:50:48.259+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:50:48.259+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:50:48.272+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:50:48.271+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:50:48.273+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:50:48.292+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-24T20:51:18.435+0000] {processor.py:154} INFO - Started process (PID=3676) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:51:18.437+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:51:18.438+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:51:18.438+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:51:18.449+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:51:18.448+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:51:18.450+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:51:18.474+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-24T20:51:49.045+0000] {processor.py:154} INFO - Started process (PID=3739) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:51:49.046+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:51:49.048+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:51:49.048+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:51:49.061+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:51:49.059+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:51:49.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:51:49.081+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-07-24T20:52:35.141+0000] {processor.py:154} INFO - Started process (PID=3802) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:52:35.143+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:52:35.143+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:52:35.143+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:52:35.156+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:52:35.152+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:52:35.158+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:52:35.178+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-07-24T20:53:05.204+0000] {processor.py:154} INFO - Started process (PID=3857) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:53:05.205+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:53:05.206+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:53:05.206+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:53:05.215+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:53:05.214+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:53:05.215+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:53:05.233+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.034 seconds
[2024-07-24T20:53:36.014+0000] {processor.py:154} INFO - Started process (PID=3920) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:53:36.017+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:53:36.018+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:53:36.018+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:53:36.029+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:53:36.027+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:53:36.029+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:53:36.043+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:54:06.761+0000] {processor.py:154} INFO - Started process (PID=3984) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:54:06.763+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:54:06.765+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:54:06.765+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:54:06.776+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:54:06.775+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:54:06.776+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:54:06.789+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:54:37.409+0000] {processor.py:154} INFO - Started process (PID=4048) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:54:37.411+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:54:37.414+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:54:37.414+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:54:37.423+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:54:37.422+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:54:37.424+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:54:37.436+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T20:55:08.094+0000] {processor.py:154} INFO - Started process (PID=4112) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:55:08.097+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:55:08.099+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:55:08.099+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:55:08.113+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:55:08.112+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:55:08.114+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:55:08.132+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-07-24T20:55:38.860+0000] {processor.py:154} INFO - Started process (PID=4176) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:55:38.861+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:55:38.863+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:55:38.863+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:55:38.871+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:55:38.870+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:55:38.871+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:55:38.884+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-07-24T20:56:09.474+0000] {processor.py:154} INFO - Started process (PID=4240) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:56:09.477+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:56:09.478+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:56:09.478+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:56:09.483+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:56:09.483+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:56:09.484+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:56:09.499+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.027 seconds
[2024-07-24T20:56:40.292+0000] {processor.py:154} INFO - Started process (PID=4295) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:56:40.293+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:56:40.294+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:56:40.294+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:56:40.312+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:56:40.310+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:56:40.313+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:56:40.342+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2024-07-24T20:57:10.598+0000] {processor.py:154} INFO - Started process (PID=4359) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:57:10.601+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:57:10.603+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:57:10.603+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:57:10.614+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:57:10.613+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:57:10.614+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:57:10.625+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.033 seconds
[2024-07-24T20:57:41.498+0000] {processor.py:154} INFO - Started process (PID=4423) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:57:41.500+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:57:41.502+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:57:41.502+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:57:41.512+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:57:41.511+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:57:41.513+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:57:41.528+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-24T20:58:12.425+0000] {processor.py:154} INFO - Started process (PID=4487) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:58:12.427+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:58:12.429+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:58:12.429+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:58:12.442+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:58:12.441+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:58:12.442+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:58:12.459+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-24T20:58:43.377+0000] {processor.py:154} INFO - Started process (PID=4551) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:58:43.378+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:58:43.381+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:58:43.381+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:58:43.390+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:58:43.390+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:58:43.391+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:58:43.406+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-24T20:59:14.343+0000] {processor.py:154} INFO - Started process (PID=4615) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:59:14.344+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:59:14.344+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:59:14.344+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:59:14.356+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:59:14.355+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:59:14.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:59:14.374+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-24T20:59:45.198+0000] {processor.py:154} INFO - Started process (PID=4679) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T20:59:45.200+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T20:59:45.202+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:59:45.202+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T20:59:45.216+0000] {logging_mixin.py:120} INFO - [2024-07-24T20:59:45.215+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T20:59:45.216+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T20:59:45.233+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-07-24T21:00:16.056+0000] {processor.py:154} INFO - Started process (PID=4743) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:00:16.058+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:00:16.060+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:00:16.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:00:16.073+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:00:16.072+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:00:16.074+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:00:16.091+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-07-24T21:00:46.949+0000] {processor.py:154} INFO - Started process (PID=4798) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:00:46.951+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:00:46.953+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:00:46.953+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:00:46.967+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:00:46.966+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:00:46.968+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:00:46.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-07-24T21:01:17.022+0000] {processor.py:154} INFO - Started process (PID=4862) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:01:17.025+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:01:17.029+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:01:17.028+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:01:17.039+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:01:17.038+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:01:17.039+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:01:17.052+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-07-24T21:01:47.081+0000] {processor.py:154} INFO - Started process (PID=4926) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:01:47.083+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:01:47.084+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:01:47.084+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:01:47.094+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:01:47.093+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:01:47.094+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:01:47.111+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-07-24T21:02:18.087+0000] {processor.py:154} INFO - Started process (PID=4989) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:02:18.090+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:02:18.091+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:02:18.091+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:02:18.100+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:02:18.099+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:02:18.100+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:02:18.115+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.032 seconds
[2024-07-24T21:02:48.926+0000] {processor.py:154} INFO - Started process (PID=5052) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:02:48.927+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:02:48.927+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:02:48.927+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:02:48.931+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:02:48.931+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:02:48.932+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:02:48.943+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.018 seconds
[2024-07-24T21:03:19.554+0000] {processor.py:154} INFO - Started process (PID=5116) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:03:19.554+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:03:19.555+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:03:19.555+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:03:19.565+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:03:19.564+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:03:19.565+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:03:19.581+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T21:03:50.236+0000] {processor.py:154} INFO - Started process (PID=5180) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:03:50.239+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:03:50.240+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:03:50.239+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:03:50.248+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:03:50.247+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:03:50.248+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:03:50.262+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.031 seconds
[2024-07-24T21:04:21.082+0000] {processor.py:154} INFO - Started process (PID=5235) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:04:21.084+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:04:21.086+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:04:21.086+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:04:21.099+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:04:21.098+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:04:21.100+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:04:21.122+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-07-24T21:04:51.883+0000] {processor.py:154} INFO - Started process (PID=5299) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:04:51.885+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:04:51.886+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:04:51.886+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:04:51.898+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:04:51.897+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:04:51.899+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:04:51.918+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-07-24T21:05:22.648+0000] {processor.py:154} INFO - Started process (PID=5362) to work on /opt/airflow/dags/test_dag.py
[2024-07-24T21:05:22.650+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-07-24T21:05:22.651+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:05:22.651+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-07-24T21:05:22.667+0000] {logging_mixin.py:120} INFO - [2024-07-24T21:05:22.665+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 5, in <module>
    from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
ModuleNotFoundError: No module named 'airflow.providers.cncf.kubernetes.operators.pod'
[2024-07-24T21:05:22.668+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-07-24T21:05:22.692+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
